server:
  port: 10030
  servlet:
    context-path: /bank
  error:
    include-message: always
logging:
  level:
    ru.domclick.account: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 4
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true




